# Generated by Django 4.2.3 on 2023-08-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('user_name', models.CharField(blank=True, default='User', max_length=20)),
                ('mov1', models.CharField(blank=True, default='The Shawshank Redemption', max_length=20, null=True)),
                ('mov2', models.CharField(blank=True, default='The Godfather', max_length=25, null=True)),
                ('mov3', models.CharField(blank=True, default='The Dark Knight', max_length=25, null=True)),
                ('mov4', models.CharField(blank=True, default='Pulp Fiction', max_length=25, null=True)),
                ('mov5', models.CharField(blank=True, default='American History X', max_length=25, null=True)),
                ('weekT1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('weekT2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('weekT3', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('weekT4', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('dailyT1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('dailyT2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('dailyT3', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('dailyT4', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('totalWatchTime', models.FloatField(default=0.0)),
                ('weeklyWatchTime', models.FloatField(default=0.0)),
                ('rewardPoints', models.IntegerField(default=0)),
            ],
        ),
    ]
